spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://localhost:8080"]
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
