services:
  iwa-offer-db:
    # nom du container = hostname sur le réseau
    container_name: iwa-offer-db
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      GATEWAY_MS_URI: http://iwa-gateway-app:8080
    volumes:
      - iwa-offer-db-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432 # host:container
    networks:
      - iwa-offer-network

  iwa-offer-app:
    container_name: iwa-offer-app
    build: .
    environment:
      spring.datasource.url: "jdbc:postgresql://iwa-offer-db:5432/${POSTGRES_DB}"
      spring.datasource.username: $POSTGRES_USER
      spring.datasource.password: $POSTGRES_PASSWORD
      spring.datasource.name: $POSTGRES_DB
      jwt.secret: $JWT_SECRET
      spring.kafka.bootstrap-servers: kafka1:9092
      GATEWAY_MS_URI: iwa-gateway-app:8080
    depends_on:
      - iwa-offer-db
    ports:
      - 8082:8080
    networks:
      - iwa-offer-network
      - kafka_iwa-kafka-network
      - gateway

volumes:
  iwa-offer-db-volume:
    driver: local

networks:
  iwa-offer-network:
  kafka_iwa-kafka-network:
    external: true
  gateway:
    external: true
