spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
#            allowed-origin-patterns: .*
            allowedOrigins: ${GATEWAY_MS_URI}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE