package fr.polytech.ig5.mnm.offerms.models;

public enum SectorType {
    AGRICULTURE_PECHE,
    ARTS,
    BANQUE_ASSURANCE_IMMOBILIER,
    COMMERCE_GRANDE_DISTRIBUTION,
    COM_MEDIA,
    CONSTRUCTION_BATIMENT_TRAVAUX_PUBLICS,
    HOTELLERIE_RESTAURATION,
    TOURISME_LOISIRS,
    INDUSTRIE

}
