version: '3,9'

services:

  # = = = = user-ms containers = = = = #
  iwa-user-db:
    # nom du container = hostname sur le network
    container_name: iwa-user-db
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: $DB_NAME_USERMS
      POSTGRES_USER: $DB_USER_USERMS
      POSTGRES_PASSWORD: $DB_PASSWORD_USERMS
    volumes:
      - iwa-user-db-volume:/var/lib/postgresql/data
    ports:
      - $DB_PORT_USERMS:5432 # host:container
    networks:
      - iwa-user-network

  iwa-user-app:
    container_name: iwa-user-app
    build: .
    environment:
      spring.datasource.url: "jdbc:postgresql://iwa-user-db:5432/${DB_NAME_USERMS}"
      spring.datasource.username: $DB_USER_USERMS
      spring.datasource.password: $DB_PASSWORD_USERMS
      spring.datasource.name: $DB_NAME_USERMS
      keycloak.auth-server-url: "http://localhost:${$APP_PORT_KEYCLOAK}/auth"
      keycloak.realm: iwa
      keycloak.public-client: true
      keycloak.resource: iwa-user-ms
    ports:
      - $APP_PORT_USERMS:8080
    networks:
      - iwa-user-network

  # = = = = keycloak containers = = = = #
  iwa-keycloak:
    container_name: iwa-keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    networks:
      - iwa-keycloak-network
    environment:
      DB_VENDOR: $DB_VENDOR_KEYCLOAK
      DB_DATABASE: $DB_NAME_KEYCLOAK
      DB_ADDR: $DB_NAME_KEYCLOAK
      DB_USER: $DB_USER_KEYCLOAK
      DB_PASSWORD: $DB_PASSWORD_KEYCLOAK
      DB_PORT: $DB_PORT_KEYCLOAK
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      PORT: $APP_PORT_KEYCLOAK
    ports:
      - $APP_PORT_KEYCLOAK:8080

  iwa-keycloak-db:
    container_name: iwa-keycloak-db
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: $DB_NAME_KEYCLOAK
      POSTGRES_USER: $DB_USER_KEYCLOAK
      POSTGRES_PASSWORD: $DB_PASSWORD_KEYCLOAK
    volumes:
      - iwa-keycloak-db-volume:/var/lib/postgresql/data
    ports:
      - $DB_PORT_KEYCLOAK:5432 # host:container
    networks:
      - iwa-keycloak-network

volumes:
  iwa-user-db-volume:
    driver: local
  iwa-keycloak-db-volume:
    driver: local

networks:
  iwa-user-network:
  iwa-keycloak-network:
