services:
  iwa-user-db:
    # nom du container = hostname sur le réseau
    container_name: iwa-user-db
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - iwa-user-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432 # host:container
    networks:
      - iwa-user-network

  iwa-user-app:
    container_name: iwa-user-app
    build: .
    environment:
      spring.datasource.url: jdbc:postgresql://iwa-user-db:5432/postgres
      #DATABASE_HOST: postgres-db # faut que ce soit le hostname de la database
    ports:
      - 8080:8080
    networks:
      - iwa-user-network

volumes:
  iwa-user-db-volume:
    driver: local

networks:
  iwa-user-network:
