spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${GATEWAY_MS_URI}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
