services:
  iwa-gateway-app:
    container_name: iwa-gateway-app
    build: .
    ports:
      - 8080:8080
    networks:
      - gateway
    environment:
      USER_MS_URI: iwa-user-app:8080

networks:
  gateway:
    name: "gateway"
