services:
  iwa-gateway-app:
    container_name: iwa-gateway-app
    build: .
    ports:
      - 8080:8080
    networks:
      - gateway
      - frontend
    environment:
      USER_MS_URI: http://iwa-user-app:8080
      OFFER_MS_URI: http://iwa-offer-app:8080
      RECRUITMENT_MS_URI: http://iwa-recruitment-app:8080
      FRONTEND_URI: $FRONTEND_URI

networks:
  gateway:
    name: "gateway"
  frontend:
    external: true
