version: "3"
services:
  zookeeper1:
    image: 'bitnami/zookeeper:latest'
    networks:
      - iwa-kafka-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: 'bitnami/kafka:latest'
    #Specifying container name => not suffixed by project name
    container_name: 'kafka1'
    networks:
      - iwa-kafka-network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper1

networks:
  iwa-kafka-network:
