services:
  iwa-recruitment-db:
    # nom du container = hostname sur le réseau
    container_name: iwa-recruitment-db
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - iwa-recruitment-db-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432 # host:container
    networks:
      - iwa-recruitment-network

  iwa-recruitment-app:
    container_name: iwa-recruitment-app
    build: .
    environment:
      spring.datasource.url: "jdbc:postgresql://iwa-recruitment-db:5432/${POSTGRES_DB}"
      spring.datasource.username: $POSTGRES_USER
      spring.datasource.password: $POSTGRES_PASSWORD
      spring.datasource.name: $POSTGRES_DB
      GATEWAY_MS_URI: iwa-gateway-app:8080
      spring.kafka.bootstrap-servers: kafka1:9092
    ports:
      - 8083:8080
    networks:
      - iwa-recruitment-network
      - kafka_iwa-kafka-network
      - gateway

volumes:
  iwa-recruitment-db-volume:
    driver: local

networks:
  iwa-recruitment-network:
  kafka_iwa-kafka-network:
    external: true
  gateway:
    external: true
